// packages/lectroids-angular/src/lib/button/button.component.ts
import { Component, computed, Input } from '@angular/core';
import { twMerge } from 'tailwind-merge';

import {
  type ButtonSize,
  ButtonStyles,
  type ButtonType,
  type ButtonVariant,
} from '@yoyodyne/lectroids-common';

@Component({
  selector: 'button',
  standalone: true,
  imports: [],
  template: `<ng-content />`,
  host: {
    '[type]': 'type',
    '[class]': 'classes()',
  },
})
export class ButtonComponent {
  @Input() type: ButtonType = 'button';
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'medium';

  classes = computed(() => {
    // tailwind merge will clean up any conflicts
    return twMerge(ButtonStyles({ variant: this.variant, size: this.size }));
  });
}

// packages/lectroids-react/src/lib/Button/Button.tsx
import { FC } from 'react';
import { twMerge } from 'tailwind-merge';

import { type ButtonProps, ButtonStyles } from '@yoyodyne/lectroids-common';

const Button: FC<ButtonProps> = ({ variant, size, className, ...props }) => {
  return <button {...props} className={twMerge(ButtonStyles({ variant, size }), className)} />;
};

export default Button;
